### ISSUE TITLE
Do a brief touch up on Dreamer's landing page

### ISSUE THREAD

**Issue by Teddarific** [Teddarific/dreamer#28]

**Comment by alexdanilowicz** [comment]
whatever we do here, let's add a "this site was built with dreamer"

also I don't think we need this until we start getting customers. not worth the effort

**Comment by Teddarific** [comment]
I didn't end up adding "This site was built with dreamer" because my brief touch ups were just adding a "Contact Us" in the bottom right + changing up the spacing a little bit. Don't think its particularly impressive if its built by dreamer LOL
